# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KvIjJapMbvNZNFJo6bYAQhcvgK8h0As
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 2 * np.pi, 500)

y = np.sin(x)

plt.figure(figsize=(8, 5))
plt.plot(x, y, label="y = sin(x)", color="blue")
plt.title("Sinus funksiyasi grafigi")
plt.xlabel("x (radianlarda)")
plt.ylabel("y")
plt.axhline(0, color='black', linewidth=0.8, linestyle="--")
plt.axvline(0, color='black', linewidth=0.8, linestyle="--")
plt.grid(alpha=0.5)
plt.legend()
plt.show()